// Synonyma tokenů pro párování jmen (po odstranění diakritiky, malými písmeny).
// Obě strany se normalizují stejně, takže stačí mapovat české exonymum i cizí tvar na jeden tvar.
// Rozšiřuj podle toho, co se objevuje ve frontě nepárovaných zápasů.
export const NAME_SYNONYMS: Record<string, string> = {
  // obecné zkratky
  utd: 'united',
  untd: 'united',
  st: 'saint',
  sv: 'sv',
  man: 'manchester',
  ny: 'new york',
  nyr: 'new york rangers',
  la: 'los angeles',
  gs: 'golden state',
  gsw: 'golden state warriors',
  okc: 'oklahoma city',
  sa: 'san antonio',
  internazionale: 'inter',
  atl: 'atletico',
  dyn: 'dynamo',
  dinamo: 'dynamo',
  gladbach: 'monchengladbach',
  mgladbach: 'monchengladbach',
  psg: 'paris saint germain',
  bvb: 'dortmund',
  wolves: 'wolverhampton',
  spurs: 'spurs',
  hotspur: '',
  republika: '',
  republic: '',
  rep: '',
  // města – česká exonyma / místní tvary
  pilsen: 'plzen',
  prague: 'praha',
  prag: 'praha',
  brunn: 'brno',
  ostrau: 'ostrava',
  mnichov: 'munich',
  munchen: 'munich',
  muenchen: 'munich',
  zahreb: 'zagreb',
  bruggy: 'brugge',
  bruges: 'brugge',
  neapol: 'napoli',
  naples: 'napoli',
  rim: 'roma',
  rome: 'roma',
  turin: 'torino',
  janov: 'genoa',
  genova: 'genoa',
  benatky: 'venezia',
  venice: 'venezia',
  florencie: 'firenze',
  milan: 'milano',
  lisabon: 'lisboa',
  lisbon: 'lisboa',
  belehrad: 'beograd',
  belgrade: 'beograd',
  ateny: 'athens',
  athina: 'athens',
  solun: 'thessaloniki',
  kodan: 'copenhagen',
  kobenhavn: 'copenhagen',
  varsava: 'warsaw',
  warszawa: 'warsaw',
  krakov: 'krakow',
  viden: 'wien',
  vienna: 'wien',
  kolin: 'koln',
  cologne: 'koln',
  koeln: 'koln',
  brem: 'bremen',
  bremy: 'bremen',
  drazdany: 'dresden',
  lipsko: 'leipzig',
  norimberk: 'nurnberg',
  nuremberg: 'nurnberg',
  moskva: 'moscow',
  moskau: 'moscow',
  petrohrad: 'petersburg',
  peterburg: 'petersburg',
  kyjev: 'kyiv',
  kiev: 'kyiv',
  charkov: 'kharkiv',
  bukurest: 'bucharest',
  bucuresti: 'bucharest',
  sofie: 'sofia',
  londyn: 'london',
  pariz: 'paris',
  brusel: 'brussels',
  bruxelles: 'brussels',
  antverpy: 'antwerp',
  antwerpen: 'antwerp',
  lutych: 'liege',
  basilej: 'basel',
  curych: 'zurich',
  zenev: 'geneva',
  zeneva: 'geneva',
  geneve: 'geneva',
  helsinky: 'helsinki',
  lublan: 'ljubljana',
  budapest: 'budapest',
  // státy – česky -> anglicky
  cesko: 'czechia',
  ceska: 'czechia',
  czech: 'czechia',
  slovensko: 'slovakia',
  nemecko: 'germany',
  rakousko: 'austria',
  polsko: 'poland',
  madarsko: 'hungary',
  svycarsko: 'switzerland',
  francie: 'france',
  italie: 'italy',
  spanelsko: 'spain',
  anglie: 'england',
  skotsko: 'scotland',
  nizozemsko: 'netherlands',
  holandsko: 'netherlands',
  belgie: 'belgium',
  dansko: 'denmark',
  svedsko: 'sweden',
  norsko: 'norway',
  finsko: 'finland',
  rusko: 'russia',
  ukrajina: 'ukraine',
  chorvatsko: 'croatia',
  srbsko: 'serbia',
  slovinsko: 'slovenia',
  recko: 'greece',
  turecko: 'turkey',
  turkiye: 'turkey',
  portugalsko: 'portugal',
  kanada: 'canada',
  spojene: 'usa',
  staty: '',
  lotyssko: 'latvia',
  litva: 'lithuania',
  estonsko: 'estonia',
  belorusko: 'belarus',
  kazachstan: 'kazakhstan',
  brazilie: 'brazil',
  kolumbie: 'colombia',
  ekvador: 'ecuador',
  bolivie: 'bolivia',
  mexiko: 'mexico',
  kostarika: 'costa rica',
  jamajka: 'jamaica',
  irsko: 'ireland',
  island: 'iceland',
  gruzie: 'georgia',
  armenie: 'armenia',
  azerbajdzan: 'azerbaijan',
  albanie: 'albania',
  cerna: 'montenegro',
  hora: '',
  bosna: 'bosnia',
  hercegovina: '',
  makedonie: 'macedonia',
  rumunsko: 'romania',
  bulharsko: 'bulgaria',
  kypr: 'cyprus',
  lucembursko: 'luxembourg',
  lichtenstejnsko: 'liechtenstein',
  izrael: 'israel',
  saudska: 'saudi',
  arabie: 'arabia',
  katar: 'qatar',
  iran: 'iran',
  irak: 'iraq',
  jordansko: 'jordan',
  syrie: 'syria',
  libanon: 'lebanon',
  uzbekistan: 'uzbekistan',
  thajsko: 'thailand',
  indonesie: 'indonesia',
  malajsie: 'malaysia',
  filipiny: 'philippines',
  japonsko: 'japan',
  cina: 'china',
  indie: 'india',
  australie: 'australia',
  novy: 'new',
  zeland: 'zealand',
  maroko: 'morocco',
  alzirsko: 'algeria',
  tunisko: 'tunisia',
  egypt: 'egypt',
  nigerie: 'nigeria',
  kamerun: 'cameroon',
  kongo: 'congo',
  pobrezi: 'ivory',
  slonoviny: 'coast',
  etiopie: 'ethiopia',
  kena: 'kenya',
  tanzanie: 'tanzania',
  zambie: 'zambia',
  mosambik: 'mozambique',
  madagaskar: 'madagascar',
  mauritanie: 'mauritania',
  somalsko: 'somalia',
  gabun: 'gabon',
  oman: 'oman',
  mauretanie: 'mauritania',
  liberie: 'liberia',
  gambie: 'gambia',
  libye: 'libya',
  moldavsko: 'moldova',
  moldavie: 'moldova',
  faerske: 'faroe',
  ostrovy: 'islands',
  surinam: 'suriname',
  martinik: 'martinique',
  guinea: 'guinea',
  guinej: 'guinea',
  rovnikova: 'equatorial',
  jihoafricka: 'south africa',
  jizni: 'south',
  severni: 'north',
  korea: 'korea',
};

/**
 * Kódy týmů NBA/NHL – aplikují se jen na tokeny psané VELKÝMI písmeny ("PHX Suns", "SA Spurs"),
 * aby "min" nebo "was" v běžném jméně nic nerozbilo.
 */
export const TEAM_CODES: Record<'basketball' | 'hockey', Record<string, string>> = {
  basketball: {
    ATL: 'atlanta', BOS: 'boston', BKN: 'brooklyn', CHA: 'charlotte', CHI: 'chicago', CLE: 'cleveland', DAL: 'dallas',
    DEN: 'denver', DET: 'detroit', GSW: 'golden state', HOU: 'houston', IND: 'indiana', LAC: 'los angeles clippers',
    LAL: 'los angeles lakers', MEM: 'memphis', MIA: 'miami', MIL: 'milwaukee', MIN: 'minnesota', NOP: 'new orleans',
    NYK: 'new york knicks', OKC: 'oklahoma city', ORL: 'orlando', PHI: 'philadelphia', PHX: 'phoenix', POR: 'portland',
    SAC: 'sacramento', SAS: 'san antonio', SA: 'san antonio', TOR: 'toronto', UTA: 'utah', WAS: 'washington', NO: 'new orleans',
  },
  hockey: {
    ANA: 'anaheim', BOS: 'boston', BUF: 'buffalo', CGY: 'calgary', CAR: 'carolina', CHI: 'chicago', COL: 'colorado',
    CBJ: 'columbus', DAL: 'dallas', DET: 'detroit', EDM: 'edmonton', FLA: 'florida', LAK: 'los angeles', MIN: 'minnesota',
    MTL: 'montreal', NSH: 'nashville', NJD: 'new jersey', NYI: 'new york islanders', NYR: 'new york rangers', OTT: 'ottawa',
    PHI: 'philadelphia', PIT: 'pittsburgh', SJS: 'san jose', SEA: 'seattle', STL: 'st louis', TBL: 'tampa bay',
    TOR: 'toronto', UTA: 'utah', VAN: 'vancouver', VGK: 'vegas', WSH: 'washington', WPG: 'winnipeg',
  },
};
